# Generated by Django 6.1 on 2026-08-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_vehiculo', models.CharField(max_length=100)),
                ('marca', models.CharField(max_length=100)),
                ('modelo', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('color', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=100)),
                ('kilometraje', models.IntegerField()),
                ('fecha_carga', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
