# Generated by Django 6.1 on 2026-09-17 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehiculos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipamiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='vehiculo',
            name='equipamientos',
            field=models.ManyToManyField(blank=True, related_name='vehiculos', to='vehiculos.equipamiento'),
        ),
    ]
